name: Android

on: [push, pull_request]

env:
  ANDROID_MINIMUM_PLATFORM: 24
  ANDROID_TARGET_PLATFORM: 36
  DOCKERIMG: archlinux:latest
  ARCH_ROOT_URL: https://mirror.rackspace.com/archlinux
  NJOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - target_arch: armeabi-v7a:arm64-v8a:x86_64
           upload: 1
           enable_ads: 0
         - target_arch: armeabi-v7a:arm64-v8a:x86_64
           upload: 1
           enable_ads: 1
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      UPLOAD: ${{ matrix.upload }}
      ENABLE_ADS: ${{ matrix.enable_ads }}
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ env.DOCKERIMG }}
        options: >-
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ github.ref }}
          -e GITHUB_SERVER_URL=${{ github.server_url }}
          -e GITHUB_REPOSITORY=${{ github.repository }}
          -e GITHUB_RUN_ID=${{ github.run_id }}
          -e GIT_COMMIT_HASH=${{ github.sha }}
          -e GIT_BRANCH_NAME=${{ github.ref_name }}
          -e KEYSTORE_DATA=${{ secrets.KEYSTORE_DATA }}
          -e KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}
          -e KEYSTORE_KEY_ALIAS=${{ secrets.KEYSTORE_KEY_ALIAS }}
          -e ANDROID_KEY_PASS=${{ secrets.ANDROID_KEY_PASS }}
          -e FILE_PASSWORD=${{ secrets.FILE_PASSWORD }}
          -e DOCKERIMG=${{ env.DOCKERIMG }}
          -e ARCH_ROOT_URL=${{ env.ARCH_ROOT_URL }}
          -e ANDROID_MINIMUM_PLATFORM=${{ env.ANDROID_MINIMUM_PLATFORM }}
          -e ANDROID_TARGET_PLATFORM=${{ env.ANDROID_TARGET_PLATFORM }}
          -e TARGET_ARCH=${{ env.TARGET_ARCH }}
          -e NJOBS=${{ env.NJOBS }}
          -e UPLOAD=${{ matrix.upload }}
          -e ENABLE_ADS=${{ matrix.enable_ads }}
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/android/install_deps.sh
          ./ports/ci/android/install_deps.sh
          echo
          echo Release Build
          echo
          chmod +x ports/ci/android/build.sh
          ./ports/ci/android/build.sh
          echo
          echo Release Deploy
          echo
          chmod +x ports/ci/android/deploy.sh
          ./ports/ci/android/deploy.sh
          echo
          echo Compress files
          echo
          chmod +x ports/ci/android/compress.sh
          ./ports/ci/android/compress.sh
    - name: Daily build
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ env.DOCKERIMG }}
        options: >-
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ github.ref }}
          -e GITHUB_SERVER_URL=${{ github.server_url }}
          -e GITHUB_REPOSITORY=${{ github.repository }}
          -e GITHUB_RUN_ID=${{ github.run_id }}
          -e GIT_COMMIT_HASH=${{ github.sha }}
          -e GIT_BRANCH_NAME=${{ github.ref_name }}
          -e KEYSTORE_DATA=${{ secrets.KEYSTORE_DATA }}
          -e KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}
          -e KEYSTORE_KEY_ALIAS=${{ secrets.KEYSTORE_KEY_ALIAS }}
          -e ANDROID_KEY_PASS=${{ secrets.ANDROID_KEY_PASS }}
          -e FILE_PASSWORD=${{ secrets.FILE_PASSWORD }}
          -e DOCKERIMG=${{ env.DOCKERIMG }}
          -e ARCH_ROOT_URL=${{ env.ARCH_ROOT_URL }}
          -e ANDROID_MINIMUM_PLATFORM=${{ env.ANDROID_MINIMUM_PLATFORM }}
          -e ANDROID_TARGET_PLATFORM=${{ env.ANDROID_TARGET_PLATFORM }}
          -e TARGET_ARCH=${{ env.TARGET_ARCH }}
          -e NJOBS=${{ env.NJOBS }}
          -e UPLOAD=${{ matrix.upload }}
          -e ENABLE_ADS=${{ matrix.enable_ads }}
          -e DAILY_BUILD=1
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/android/install_deps.sh
          ./ports/ci/android/install_deps.sh
          echo
          echo Daily Build
          echo
          chmod +x ports/ci/android/build.sh
          ./ports/ci/android/build.sh
          echo
          echo Daily Deploy
          echo
          chmod +x ports/ci/android/deploy.sh
          ./ports/ci/android/deploy.sh
          echo
          echo Compress files
          echo
          chmod +x ports/ci/android/compress.sh
          ./ports/ci/android/compress.sh
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v4
      if: ${{ matrix.upload }}
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          webcamoid-packages/android/*
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        repository: webcamoid/WebcamoidPrivate
        files: webcamoid-packages/android/*
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.upload && github.ref == 'refs/heads/master' }}
      with:
        repository: webcamoid/WebcamoidPrivate
        body: "${{ github.event.head_commit.message }} (commit: [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}))<hr>**Note**: Ignore the commit information of the tag, the files in the release keep updating with every new build, these packages were built from [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}) commit."
        prerelease: true
        files: webcamoid-packages/android/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
